// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0
{
    using Models;

    /// <summary>
    /// </summary>
    public partial interface IUWProgramApiClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        Microsoft.Rest.ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IUwExport.
        /// </summary>
        IUwExport UwExport { get; }

        /// <summary>
        /// Gets the IUwProgramGlobalExpertData.
        /// </summary>
        IUwProgramGlobalExpertData UwProgramGlobalExpertData { get; }

        /// <summary>
        /// Gets the IUwProgramRepository.
        /// </summary>
        IUwProgramRepository UwProgramRepository { get; }

        /// <summary>
        /// Gets the IUWProgram.
        /// </summary>
        IUWProgram UWProgram { get; }

        /// <summary>
        /// Gets the IUWProgramCheckList.
        /// </summary>
        IUWProgramCheckList UWProgramCheckList { get; }

        /// <summary>
        /// Gets the IUwCluster.
        /// </summary>
        IUwCluster UwCluster { get; }

        /// <summary>
        /// Gets the IUWProgramLayer.
        /// </summary>
        IUWProgramLayer UWProgramLayer { get; }

        /// <summary>
        /// Gets the IUWProgramQuotaShare.
        /// </summary>
        IUWProgramQuotaShare UWProgramQuotaShare { get; }

        /// <summary>
        /// Gets the IUWProgramRiskObject.
        /// </summary>
        IUWProgramRiskObject UWProgramRiskObject { get; }

        /// <summary>
        /// Gets the IUwProgramTermCondition.
        /// </summary>
        IUwProgramTermCondition UwProgramTermCondition { get; }

        /// <summary>
        /// Gets the IUwProgramTermConditionSpecific.
        /// </summary>
        IUwProgramTermConditionSpecific UwProgramTermConditionSpecific { get; }

        /// <summary>
        /// Gets the IUwpTermsConditionApplication.
        /// </summary>
        IUwpTermsConditionApplication UwpTermsConditionApplication { get; }

    }
}
