// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class ApiError
    {
        /// <summary>
        /// Initializes a new instance of the ApiError class.
        /// </summary>
        public ApiError() { }

        /// <summary>
        /// Initializes a new instance of the ApiError class.
        /// </summary>
        /// <param name="errorType">Possible values include: 'InputError',
        /// 'ConflictError', 'UnknownError', 'IncorrectUrlError',
        /// 'UnauthorizedError', 'UnauthenticatedError'</param>
        public ApiError(string errorType = default(string), string errorId = default(string), string message = default(string), string description = default(string), System.Collections.Generic.IList<ApiInputErrorDetail> inputErrors = default(System.Collections.Generic.IList<ApiInputErrorDetail>))
        {
            ErrorType = errorType;
            ErrorId = errorId;
            Message = message;
            Description = description;
            InputErrors = inputErrors;
        }

        /// <summary>
        /// Gets or sets possible values include: 'InputError',
        /// 'ConflictError', 'UnknownError', 'IncorrectUrlError',
        /// 'UnauthorizedError', 'UnauthenticatedError'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ErrorType")]
        public string ErrorType { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ErrorId")]
        public string ErrorId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "InputErrors")]
        public System.Collections.Generic.IList<ApiInputErrorDetail> InputErrors { get; set; }

    }
}
