// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class ApplyClause
    {
        /// <summary>
        /// Initializes a new instance of the ApplyClause class.
        /// </summary>
        public ApplyClause() { }

        /// <summary>
        /// Initializes a new instance of the ApplyClause class.
        /// </summary>
        public ApplyClause(System.Collections.Generic.IList<TransformationNode> transformations = default(System.Collections.Generic.IList<TransformationNode>))
        {
            Transformations = transformations;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Transformations")]
        public System.Collections.Generic.IList<TransformationNode> Transformations { get; private set; }

    }
}
