// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class ClusterDto
    {
        /// <summary>
        /// Initializes a new instance of the ClusterDto class.
        /// </summary>
        public ClusterDto() { }

        /// <summary>
        /// Initializes a new instance of the ClusterDto class.
        /// </summary>
        public ClusterDto(int? clusterId = default(int?), int? underwritingProgramId = default(int?), string name = default(string), string creator = default(string), string modifier = default(string), System.DateTime? creationDate = default(System.DateTime?), System.DateTime? modificationDate = default(System.DateTime?), System.Collections.Generic.IList<ClusterRiskObjectDto> clusterRiskObjects = default(System.Collections.Generic.IList<ClusterRiskObjectDto>))
        {
            ClusterId = clusterId;
            UnderwritingProgramId = underwritingProgramId;
            Name = name;
            Creator = creator;
            Modifier = modifier;
            CreationDate = creationDate;
            ModificationDate = modificationDate;
            ClusterRiskObjects = clusterRiskObjects;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ClusterId")]
        public int? ClusterId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UnderwritingProgramId")]
        public int? UnderwritingProgramId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Creator")]
        public string Creator { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Modifier")]
        public string Modifier { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CreationDate")]
        public System.DateTime? CreationDate { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ModificationDate")]
        public System.DateTime? ModificationDate { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ClusterRiskObjects")]
        public System.Collections.Generic.IList<ClusterRiskObjectDto> ClusterRiskObjects { get; set; }

    }
}
