// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class ClusterRiskObjectDto
    {
        /// <summary>
        /// Initializes a new instance of the ClusterRiskObjectDto class.
        /// </summary>
        public ClusterRiskObjectDto() { }

        /// <summary>
        /// Initializes a new instance of the ClusterRiskObjectDto class.
        /// </summary>
        public ClusterRiskObjectDto(int? riskObjectId = default(int?), System.DateTime? creationDate = default(System.DateTime?), System.DateTime? modificationDate = default(System.DateTime?))
        {
            RiskObjectId = riskObjectId;
            CreationDate = creationDate;
            ModificationDate = modificationDate;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "RiskObjectId")]
        public int? RiskObjectId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CreationDate")]
        public System.DateTime? CreationDate { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ModificationDate")]
        public System.DateTime? ModificationDate { get; set; }

    }
}
