// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class CountQueryOption
    {
        /// <summary>
        /// Initializes a new instance of the CountQueryOption class.
        /// </summary>
        public CountQueryOption() { }

        /// <summary>
        /// Initializes a new instance of the CountQueryOption class.
        /// </summary>
        public CountQueryOption(ODataQueryContext context = default(ODataQueryContext), string rawValue = default(string), bool? value = default(bool?), object validator = default(object))
        {
            Context = context;
            RawValue = rawValue;
            Value = value;
            Validator = validator;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Context")]
        public ODataQueryContext Context { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "RawValue")]
        public string RawValue { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Value")]
        public bool? Value { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Validator")]
        public object Validator { get; set; }

    }
}
