// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class EdmReferentialConstraintPropertyPair
    {
        /// <summary>
        /// Initializes a new instance of the
        /// EdmReferentialConstraintPropertyPair class.
        /// </summary>
        public EdmReferentialConstraintPropertyPair() { }

        /// <summary>
        /// Initializes a new instance of the
        /// EdmReferentialConstraintPropertyPair class.
        /// </summary>
        public EdmReferentialConstraintPropertyPair(IEdmStructuralProperty dependentProperty = default(IEdmStructuralProperty), IEdmStructuralProperty principalProperty = default(IEdmStructuralProperty))
        {
            DependentProperty = dependentProperty;
            PrincipalProperty = principalProperty;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "DependentProperty")]
        public IEdmStructuralProperty DependentProperty { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "PrincipalProperty")]
        public IEdmStructuralProperty PrincipalProperty { get; private set; }

    }
}
