// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class FilterClause
    {
        /// <summary>
        /// Initializes a new instance of the FilterClause class.
        /// </summary>
        public FilterClause() { }

        /// <summary>
        /// Initializes a new instance of the FilterClause class.
        /// </summary>
        public FilterClause(SingleValueNode expression = default(SingleValueNode), RangeVariable rangeVariable = default(RangeVariable), IEdmTypeReference itemType = default(IEdmTypeReference))
        {
            Expression = expression;
            RangeVariable = rangeVariable;
            ItemType = itemType;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Expression")]
        public SingleValueNode Expression { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "RangeVariable")]
        public RangeVariable RangeVariable { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ItemType")]
        public IEdmTypeReference ItemType { get; private set; }

    }
}
