// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class FilterQueryOption
    {
        /// <summary>
        /// Initializes a new instance of the FilterQueryOption class.
        /// </summary>
        public FilterQueryOption() { }

        /// <summary>
        /// Initializes a new instance of the FilterQueryOption class.
        /// </summary>
        public FilterQueryOption(ODataQueryContext context = default(ODataQueryContext), object validator = default(object), FilterClause filterClause = default(FilterClause), string rawValue = default(string))
        {
            Context = context;
            Validator = validator;
            FilterClause = filterClause;
            RawValue = rawValue;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Context")]
        public ODataQueryContext Context { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Validator")]
        public object Validator { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "FilterClause")]
        public FilterClause FilterClause { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "RawValue")]
        public string RawValue { get; private set; }

    }
}
