// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class IEdmEntityContainer
    {
        /// <summary>
        /// Initializes a new instance of the IEdmEntityContainer class.
        /// </summary>
        public IEdmEntityContainer() { }

        /// <summary>
        /// Initializes a new instance of the IEdmEntityContainer class.
        /// </summary>
        /// <param name="schemaElementKind">Possible values include: 'None',
        /// 'TypeDefinition', 'ValueTerm', 'Action', 'EntityContainer',
        /// 'Function'</param>
        public IEdmEntityContainer(System.Collections.Generic.IList<IEdmEntityContainerElement> elements = default(System.Collections.Generic.IList<IEdmEntityContainerElement>), string schemaElementKind = default(string), string namespaceProperty = default(string), string name = default(string))
        {
            Elements = elements;
            SchemaElementKind = schemaElementKind;
            NamespaceProperty = namespaceProperty;
            Name = name;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Elements")]
        public System.Collections.Generic.IList<IEdmEntityContainerElement> Elements { get; private set; }

        /// <summary>
        /// Gets possible values include: 'None', 'TypeDefinition',
        /// 'ValueTerm', 'Action', 'EntityContainer', 'Function'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SchemaElementKind")]
        public string SchemaElementKind { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Namespace")]
        public string NamespaceProperty { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; private set; }

    }
}
