// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class IEdmReferentialConstraint
    {
        /// <summary>
        /// Initializes a new instance of the IEdmReferentialConstraint class.
        /// </summary>
        public IEdmReferentialConstraint() { }

        /// <summary>
        /// Initializes a new instance of the IEdmReferentialConstraint class.
        /// </summary>
        public IEdmReferentialConstraint(System.Collections.Generic.IList<EdmReferentialConstraintPropertyPair> propertyPairs = default(System.Collections.Generic.IList<EdmReferentialConstraintPropertyPair>))
        {
            PropertyPairs = propertyPairs;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "PropertyPairs")]
        public System.Collections.Generic.IList<EdmReferentialConstraintPropertyPair> PropertyPairs { get; private set; }

    }
}
