// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class IEdmNavigationProperty
    {
        /// <summary>
        /// Initializes a new instance of the IEdmNavigationProperty class.
        /// </summary>
        public IEdmNavigationProperty() { }

        /// <summary>
        /// Initializes a new instance of the IEdmNavigationProperty class.
        /// </summary>
        /// <param name="onDelete">Possible values include: 'None',
        /// 'Cascade'</param>
        /// <param name="propertyKind">Possible values include: 'None',
        /// 'Structural', 'Navigation'</param>
        public IEdmNavigationProperty(IEdmNavigationProperty partner = default(IEdmNavigationProperty), string onDelete = default(string), bool? containsTarget = default(bool?), IEdmReferentialConstraint referentialConstraint = default(IEdmReferentialConstraint), string propertyKind = default(string), IEdmTypeReference type = default(IEdmTypeReference), IEdmStructuredType declaringType = default(IEdmStructuredType), string name = default(string))
        {
            Partner = partner;
            OnDelete = onDelete;
            ContainsTarget = containsTarget;
            ReferentialConstraint = referentialConstraint;
            PropertyKind = propertyKind;
            Type = type;
            DeclaringType = declaringType;
            Name = name;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Partner")]
        public IEdmNavigationProperty Partner { get; private set; }

        /// <summary>
        /// Gets possible values include: 'None', 'Cascade'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "OnDelete")]
        public string OnDelete { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ContainsTarget")]
        public bool? ContainsTarget { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ReferentialConstraint")]
        public IEdmReferentialConstraint ReferentialConstraint { get; private set; }

        /// <summary>
        /// Gets possible values include: 'None', 'Structural', 'Navigation'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "PropertyKind")]
        public string PropertyKind { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Type")]
        public IEdmTypeReference Type { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "DeclaringType")]
        public IEdmStructuredType DeclaringType { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; private set; }

    }
}
