// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class IEdmEntityContainerElement
    {
        /// <summary>
        /// Initializes a new instance of the IEdmEntityContainerElement class.
        /// </summary>
        public IEdmEntityContainerElement() { }

        /// <summary>
        /// Initializes a new instance of the IEdmEntityContainerElement class.
        /// </summary>
        /// <param name="containerElementKind">Possible values include:
        /// 'None', 'EntitySet', 'ActionImport', 'FunctionImport',
        /// 'Singleton'</param>
        public IEdmEntityContainerElement(string containerElementKind = default(string), IEdmEntityContainer container = default(IEdmEntityContainer), string name = default(string))
        {
            ContainerElementKind = containerElementKind;
            Container = container;
            Name = name;
        }

        /// <summary>
        /// Gets possible values include: 'None', 'EntitySet', 'ActionImport',
        /// 'FunctionImport', 'Singleton'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ContainerElementKind")]
        public string ContainerElementKind { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Container")]
        public IEdmEntityContainer Container { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; private set; }

    }
}
