// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class IEdmVocabularyAnnotation
    {
        /// <summary>
        /// Initializes a new instance of the IEdmVocabularyAnnotation class.
        /// </summary>
        public IEdmVocabularyAnnotation() { }

        /// <summary>
        /// Initializes a new instance of the IEdmVocabularyAnnotation class.
        /// </summary>
        public IEdmVocabularyAnnotation(string qualifier = default(string), IEdmTerm term = default(IEdmTerm), object target = default(object))
        {
            Qualifier = qualifier;
            Term = term;
            Target = target;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Qualifier")]
        public string Qualifier { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Term")]
        public IEdmTerm Term { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Target")]
        public object Target { get; private set; }

    }
}
