// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class LimitDeductibleDto
    {
        /// <summary>
        /// Initializes a new instance of the LimitDeductibleDto class.
        /// </summary>
        public LimitDeductibleDto() { }

        /// <summary>
        /// Initializes a new instance of the LimitDeductibleDto class.
        /// </summary>
        /// <param name="indemnityType">Possible values include: 'PD', 'BI',
        /// 'Combined'</param>
        /// <param name="unit">Possible values include: 'ME', 'PercentageTSI',
        /// 'NbreDays'</param>
        /// <param name="baseProperty">Possible values include: 'PerRisk',
        /// 'PerEvents'</param>
        public LimitDeductibleDto(int? id = default(int?), string indemnityType = default(string), double? value = default(double?), string unit = default(string), string baseProperty = default(string), bool? isAggregate = default(bool?))
        {
            Id = id;
            IndemnityType = indemnityType;
            Value = value;
            Unit = unit;
            BaseProperty = baseProperty;
            IsAggregate = isAggregate;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'PD', 'BI', 'Combined'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "IndemnityType")]
        public string IndemnityType { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Value")]
        public double? Value { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'ME', 'PercentageTSI',
        /// 'NbreDays'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Unit")]
        public string Unit { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'PerRisk', 'PerEvents'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Base")]
        public string BaseProperty { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "IsAggregate")]
        public bool? IsAggregate { get; set; }

    }
}
