// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class OrderByNode
    {
        /// <summary>
        /// Initializes a new instance of the OrderByNode class.
        /// </summary>
        public OrderByNode() { }

        /// <summary>
        /// Initializes a new instance of the OrderByNode class.
        /// </summary>
        /// <param name="direction">Possible values include: 'Ascending',
        /// 'Descending'</param>
        public OrderByNode(string direction = default(string))
        {
            Direction = direction;
        }

        /// <summary>
        /// Gets possible values include: 'Ascending', 'Descending'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Direction")]
        public string Direction { get; private set; }

    }
}
