// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class OrderByClause
    {
        /// <summary>
        /// Initializes a new instance of the OrderByClause class.
        /// </summary>
        public OrderByClause() { }

        /// <summary>
        /// Initializes a new instance of the OrderByClause class.
        /// </summary>
        /// <param name="direction">Possible values include: 'Ascending',
        /// 'Descending'</param>
        public OrderByClause(OrderByClause thenBy = default(OrderByClause), SingleValueNode expression = default(SingleValueNode), string direction = default(string), RangeVariable rangeVariable = default(RangeVariable), IEdmTypeReference itemType = default(IEdmTypeReference))
        {
            ThenBy = thenBy;
            Expression = expression;
            Direction = direction;
            RangeVariable = rangeVariable;
            ItemType = itemType;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ThenBy")]
        public OrderByClause ThenBy { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Expression")]
        public SingleValueNode Expression { get; private set; }

        /// <summary>
        /// Gets possible values include: 'Ascending', 'Descending'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Direction")]
        public string Direction { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "RangeVariable")]
        public RangeVariable RangeVariable { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ItemType")]
        public IEdmTypeReference ItemType { get; private set; }

    }
}
