// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class OutPutPricing
    {
        /// <summary>
        /// Initializes a new instance of the OutPutPricing class.
        /// </summary>
        public OutPutPricing() { }

        /// <summary>
        /// Initializes a new instance of the OutPutPricing class.
        /// </summary>
        public OutPutPricing(int? idLayer = default(int?), int? idRO = default(int?), string peril = default(string), double? premium = default(double?))
        {
            IdLayer = idLayer;
            IdRO = idRO;
            Peril = peril;
            Premium = premium;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "IdLayer")]
        public int? IdLayer { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "IdRO")]
        public int? IdRO { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Peril")]
        public string Peril { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Premium")]
        public double? Premium { get; set; }

    }
}
