// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class PageResultProgramDto
    {
        /// <summary>
        /// Initializes a new instance of the PageResultProgramDto class.
        /// </summary>
        public PageResultProgramDto() { }

        /// <summary>
        /// Initializes a new instance of the PageResultProgramDto class.
        /// </summary>
        public PageResultProgramDto(System.Collections.Generic.IList<ProgramDto> items = default(System.Collections.Generic.IList<ProgramDto>), string nextPageLink = default(string), long? count = default(long?))
        {
            Items = items;
            NextPageLink = nextPageLink;
            Count = count;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Items")]
        public System.Collections.Generic.IList<ProgramDto> Items { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "NextPageLink")]
        public string NextPageLink { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Count")]
        public long? Count { get; set; }

    }
}
