// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class PerilDto
    {
        /// <summary>
        /// Initializes a new instance of the PerilDto class.
        /// </summary>
        public PerilDto() { }

        /// <summary>
        /// Initializes a new instance of the PerilDto class.
        /// </summary>
        public PerilDto(int? id = default(int?), int? programId = default(int?), System.Collections.Generic.IList<LimitDeductibleDto> indemnityLimit = default(System.Collections.Generic.IList<LimitDeductibleDto>), System.Collections.Generic.IList<LimitDeductibleDto> indemnityDeductible = default(System.Collections.Generic.IList<LimitDeductibleDto>), System.Collections.Generic.IList<int?> subPerilsList = default(System.Collections.Generic.IList<int?>))
        {
            Id = id;
            ProgramId = programId;
            IndemnityLimit = indemnityLimit;
            IndemnityDeductible = indemnityDeductible;
            SubPerilsList = subPerilsList;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ProgramId")]
        public int? ProgramId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "IndemnityLimit")]
        public System.Collections.Generic.IList<LimitDeductibleDto> IndemnityLimit { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "IndemnityDeductible")]
        public System.Collections.Generic.IList<LimitDeductibleDto> IndemnityDeductible { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SubPerilsList")]
        public System.Collections.Generic.IList<int?> SubPerilsList { get; set; }

    }
}
