// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    /// <summary>
    /// Class PricingResponse.
    /// </summary>
    public partial class PricingResponse
    {
        /// <summary>
        /// Initializes a new instance of the PricingResponse class.
        /// </summary>
        public PricingResponse() { }

        /// <summary>
        /// Initializes a new instance of the PricingResponse class.
        /// </summary>
        /// <param name="premiums">Gets Premium amount.</param>
        public PricingResponse(System.Collections.Generic.IList<OutPutPricing> premiums = default(System.Collections.Generic.IList<OutPutPricing>))
        {
            Premiums = premiums;
        }

        /// <summary>
        /// Gets Premium amount.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Premiums")]
        public System.Collections.Generic.IList<OutPutPricing> Premiums { get; set; }

    }
}
