// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class PricingResultDto
    {
        /// <summary>
        /// Initializes a new instance of the PricingResultDto class.
        /// </summary>
        public PricingResultDto() { }

        /// <summary>
        /// Initializes a new instance of the PricingResultDto class.
        /// </summary>
        public PricingResultDto(int? undewritingProgramId = default(int?), int? layerId = default(int?), int? perilId = default(int?), int? riskObjectId = default(int?), double? calculatedPremium = default(double?), string creator = default(string))
        {
            UndewritingProgramId = undewritingProgramId;
            LayerId = layerId;
            PerilId = perilId;
            RiskObjectId = riskObjectId;
            CalculatedPremium = calculatedPremium;
            Creator = creator;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UndewritingProgramId")]
        public int? UndewritingProgramId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "LayerId")]
        public int? LayerId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "PerilId")]
        public int? PerilId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "RiskObjectId")]
        public int? RiskObjectId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CalculatedPremium")]
        public double? CalculatedPremium { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Creator")]
        public string Creator { get; set; }

    }
}
