// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class ProgramRiskObjectDto
    {
        /// <summary>
        /// Initializes a new instance of the ProgramRiskObjectDto class.
        /// </summary>
        public ProgramRiskObjectDto() { }

        /// <summary>
        /// Initializes a new instance of the ProgramRiskObjectDto class.
        /// </summary>
        public ProgramRiskObjectDto(int? programId = default(int?), int? riskObjectId = default(int?), int? objectOrderInProgram = default(int?))
        {
            ProgramId = programId;
            RiskObjectId = riskObjectId;
            ObjectOrderInProgram = objectOrderInProgram;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ProgramId")]
        public int? ProgramId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "RiskObjectId")]
        public int? RiskObjectId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ObjectOrderInProgram")]
        public int? ObjectOrderInProgram { get; set; }

    }
}
