// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class TermsConditionsSpecificCriteriaDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TermsConditionsSpecificCriteriaDto class.
        /// </summary>
        public TermsConditionsSpecificCriteriaDto() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TermsConditionsSpecificCriteriaDto class.
        /// </summary>
        public TermsConditionsSpecificCriteriaDto(int? id = default(int?), int? typeId = default(int?), int? operatorId = default(int?), string value = default(string), string secondValue = default(string))
        {
            Id = id;
            TypeId = typeId;
            OperatorId = operatorId;
            Value = value;
            SecondValue = secondValue;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "TypeId")]
        public int? TypeId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "OperatorId")]
        public int? OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SecondValue")]
        public string SecondValue { get; set; }

    }
}
