// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class TransformationNode
    {
        /// <summary>
        /// Initializes a new instance of the TransformationNode class.
        /// </summary>
        public TransformationNode() { }

        /// <summary>
        /// Initializes a new instance of the TransformationNode class.
        /// </summary>
        /// <param name="kind">Possible values include: 'Aggregate',
        /// 'GroupBy', 'Filter'</param>
        public TransformationNode(string kind = default(string))
        {
            Kind = kind;
        }

        /// <summary>
        /// Gets possible values include: 'Aggregate', 'GroupBy', 'Filter'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Kind")]
        public string Kind { get; private set; }

    }
}
