// <autogenerated>By AutoRest</autogenerated>

namespace UWProgramApi.v1_0.Models
{
    using System.Linq;

    public partial class UnderwritingRepositoryValueDto
    {
        /// <summary>
        /// Initializes a new instance of the UnderwritingRepositoryValueDto
        /// class.
        /// </summary>
        public UnderwritingRepositoryValueDto() { }

        /// <summary>
        /// Initializes a new instance of the UnderwritingRepositoryValueDto
        /// class.
        /// </summary>
        public UnderwritingRepositoryValueDto(int? uwRepositoryValueSeq = default(int?), int? uwRepositoryValueId = default(int?), int? value = default(int?), string code = default(string), string wording = default(string), System.DateTime? creationDate = default(System.DateTime?), System.DateTime? modificationDate = default(System.DateTime?))
        {
            UwRepositoryValueSeq = uwRepositoryValueSeq;
            UwRepositoryValueId = uwRepositoryValueId;
            Value = value;
            Code = code;
            Wording = wording;
            CreationDate = creationDate;
            ModificationDate = modificationDate;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UwRepositoryValueSeq")]
        public int? UwRepositoryValueSeq { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UwRepositoryValueId")]
        public int? UwRepositoryValueId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Value")]
        public int? Value { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Wording")]
        public string Wording { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CreationDate")]
        public System.DateTime? CreationDate { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ModificationDate")]
        public System.DateTime? ModificationDate { get; set; }

    }
}
